config/routes.rb
Flippr::Application.routes.draw do
  
  resources :users  
  resources :albums
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  
  match '/search/', to: 'tags#show'
  match '/popular/', to: "tags#index"
  match '/suggest/', to: "tags#suggest"

  root to: 'users#new'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  set_table_name 'users'
  set_primary_key 'id'

  attr_accessible :password, :first_name, :last_name, :email, :dob, 
                  :homestate, :homecity,:homecountry, 
                  :currentcity, :currentstate, :currentcountry, 
                  :education,:gender

  has_many :albums, :foreign_key => "userid" 
  has_many :photos, :through => :albums , :foreign_key => "userid"
  has_many :likes, :foreign_key => "userid"
  has_many :comments, :foreign_key => "userid"
  #has_and_belongs_to_many :friends, :class_name => 'user', :foreign
  
  
  #attr_accessor :first_name, :last_name, :password, :dob, :email
  
  def get_albums
    Album.find_by_sql([
      "SELECT albums.* 
       FROM albums
       WHERE albums.userid = ?",id])
  end

  def get_photos
    Photo.find_by_sql([
      "SELECT photos.*
       FROM photos INNER JOIN albums ON photos.albumid = albums.id
       WHERE albums.userid= ?", id])
  end

  def self.from_email(email)
    User.find_by_sql([
      "SELECT users.*
       FROM users
       WHERE users.email = ?
       LIMIT 1",email]
    ).first 
  end
  
  def self.from_id(id)
    User.find_by_sql( ["
      SELECT users.* 
      FROM users 
      WHERE users.id = ? 
      LIMIT 1", id]).first
  end

  def friends
    User.find_by_sql([
    "SELECT users.* FROM users
     WHERE users.id in (
       SELECT user2id 
       FROM friends f
       WHERE f.user1id = ?
       UNION
       SELECT user1id
       FROM friends f2
       WHERE f2.user2id = ?
      )",id,id])
  end

  def friend(userid)
    user1id = ActiveRecord::Base::sanitize(userid)
    user2id = id
    User.connection.select_all("
      INSERT INTO friends (user1id,user2id) 
      SELECT #{user1id}, #{user2id} 
      WHERE NOT EXISTS (
        SELECT * FROM friends f
        WHERE (f.user1id = #{user1id} AND f.user2id = #{user2id})
           OR (f.user1id = #{user2id} AND f.user2id = #{user1id}) );
      SELECT user2id, user1id FROM friends f
      WHERE (f.user1id = #{user1id} AND f.user2id= #{user2id}) 
         OR (f.user1id = #{user2id} AND f.user2id= #{user1id})")
  end

  def unfriend(userid)
    user1id = ActiveRecord::Base::sanitize(userid)
    user2id = id
    User.connection.select_all("
      DELETE FROM friends f
      WHERE (f.user1id = #{user1id} AND f.user2id= #{user2id}) 
         OR (f.user1id = #{user2id} AND f.user2id= #{user1id})")
  end
  
  def as_json(options)
    # this example ignores the user's options
     super(:only => [:email, :first_name, :last_name])
  end

  def name
    first_name+" "+last_name
  end

  def authenticate( pw )
    pw = password
  end
  
  def likes( pic )
    Like.find_by_sql(["
    SELECT likes.* 
    FROM likes 
    WHERE photoid = ? AND userid = ?",pic.id,id]).first
  end

  def self.sort_by_contribution
     
   ActiveRecord::Base.transaction do
     query = User.connection.select_all("
       
       SELECT u.id as cid, COUNT(c.id) as coms 
       INTO UNLOGGED tc FROM users u, comments c
       WHERE u.id = c.userid 
       GROUP BY cid; 
       
       SELECT u.id as pid, COUNT(p.id) as pics 
       INTO UNLOGGED tp FROM users u, albums a, photos p 
       WHERE u.id=a.userid AND p.albumid = a.id 
       GROUP BY pid; 
       
       SELECT * 
       FROM tp FULL JOIN tc ON tp.pid = tc.cid;
     ").map{|row| row.symbolize_keys}
     
      User.connection.select_all("drop table tc,tp;")
      
      res= query.map do |row|
        result = {}
        result[:id] = row[:cid] || row[:pid] 
        result[:user] = User.from_id(result[:id])
        
        result[:score] = 0
        result[:score] +=row[:pics].to_i if row[:pics]
        result[:score] += row[:coms].to_i if row[:coms]
        result
      end
      res.sort_by{|hsh| hsh[:score]*-1}
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user , only: [:destroy]  
  # GET /users
  # GET /users.json
  def index
    @contributors = User.sort_by_contribution
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @friends = @user.friends
    @tags = Tag.find_by_user_id(@user.id)
    @tags.inspect
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    if current_user
      redirect_to current_user
    else
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        sign_in(@user) 
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
 <%= f.label :first_name %> 
  <%= f.text_field :first_name %>
 <%= f.label :last_name %> <%= f.text_field :last_name %><br />
 <%= f.label :email %>  <%= f.email_field :email %><br />
 <%= f.label :date_of_birth %> <%= f.text_field :dob %><br />
 <%= f.label :password %>  <%= f.password_field :password %><br />
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Sign Up', :class => 'btn btn-large btn-danger'%>
  </div>
<% end %>

app/views/users/_full_form.html.erb
<%= form_for(@user) do |f| %>
 <%= f.label :first_name %> <%= f.text_field :first_name %>
 <%= f.label :last_name %> <%= f.text_field :last_name %><br />
 <%= f.label :email %>  <%= f.email_field :email %><br />
 <%= f.label :date_of_birth %> <%= f.text_field :dob %><br />
 <%= f.label :homecity %> <%= f.text_field :homecity %>
 <%= f.label :homestate %> <%= f.text_field :homestate %><br />
 <%= f.label :homecountry %> <%= f.text_field :homecountry %>
 <%= f.label :currentcity %> <%= f.text_field :currentcity %><br />
 <%= f.label :currentstate %> <%= f.text_field :currentstate %>
 <%= f.label :currentcountry %> <%= f.text_field :currentcountry %><br />
 <%= f.label :gender %> <%= f.text_field :gender %><br />
 <%= f.label :education %> <%= f.text_field :education %><br />
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Save Changes', :class => 'btn btn-large btn-danger'%>
  </div>
<% end %>

app/views/users/_profile.html.erb
<div class="row" id="profile">
	<div class="span4">
		<span class="label label-success">ABOUT</span>
		<br><br>
		<p><b>name:</b> <%= @user.name %></p>
		<p><b>date of birth:</b> <%= @user.dob.strftime("%v") %></p>
		<p><b>gender: </b><%= @user.gender || "?" %></p>
		<p><b>education: </b><%= @user.education || "?" %></p>
	</div>
	<div class="span4">
		<span class="label label-warning">HOME</span>
		<br><br>
		<p><b>city:</b> <%= @user.homecity || "?" %></p>
		<p><b>state: </b><%= @user.homestate || "?" %></p>
		<p><b>country: </b><%= @user.homecountry || "?" %></p>
	</div>
	<div class="span4">
		<span class="label label-important">COUNTRY</span>
		<br><br>
		<p><b>city:</b> <%= @user.currentcity || "?" %></p>
		<p><b>state: </b><%= @user.currentstate || "?" %></p>
		<p><b>country: </b><%= @user.currentcountry || "?" %></p>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'full_form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="row pagination-centered">
	<h1>users by contribution</h1>

	<br/>
	<br/>
	<center>
	<table>
	  <tr>
		<th>user</th>
		<th width="300">activity</th>
		<th >score</th>
	  </tr>

	<% @contributors.each do |row| %>
	<% @max = @contributors.first[:score].to_f %>
	<tr>
		<td><%= link_to "#{row[:user].name}", 
						"/users/#{row[:user].id}", 
						:class=>"btn btn-danger" ,
						:style=>"float:right;"
						%></td>
		<td>
			<div class="progress" style="margin:0;height:15px;">
				<div class="bar" style="width: <%=(100*row[:score]/@max).to_i %>%"></div>
			</div>
		</td>
		<td style="text-align:center;">
			<%= row[:score] %>
		</td>
	  </tr>
	<% end %>
	</table>
	</center>
	<br />
</div>

app/views/users/new.html.erb
<div class="pagination-centered">
<h1>welcome</h1>
<br/>

<%= render 'form' %>
</div>

app/views/users/show.html.erb
<% if flash[:notice]%>
	<p id="notice" class="pagination-centered alert-info"><%= flash[:notice]%></p>
<% end %>

<div class="pagination-centered">
<% if current_user and current_user?(@user)%>
<h1>your flippr</h1>
<br/>
<%= link_to "edit profile", edit_user_path(@user) , :class=>"btn btn-small"%>
<% else %>
<h1><%= @user.name %></h1>
<br/>
	<% if @friends.include?(current_user) %>
		<a href="/friends/<%=@user.id%>"
		   data-method="delete"
		   class="btn btn-default"
		>
		unfriend
		</a>
	<% else %>
		<a 
			href="/friends/?id=<%=@user.id%>" 
			data-method="create" 
			class="btn btn-primary">
		add as friend
		</a>
	<% end %>
<% end %>
<br/>
<br/>
<%= render "profile" %>


<h5>
<% if @user.albums.count >= 1 %>
	<hr>
	<h2><%= current_user?(@user) ? "your" : @user.name  %> albums</h2>
	<div class="row">
	<% @user.albums.each do |album| 
	   @pic = album.cover %>
		<blockquote class="img-rounded span3">
		<a href="<%= album_path(album)%>"><h4><%= album.name %></h4></a>
		<%if @pic %>
		<img src="<%= @pic.image %>" height=150 width=150>
		<% end %>
		<br/>
		<br/>
		<h6 class="muted">Album created on <%= album.date.strftime("%v")%></h6>
		<% if current_user?(@user) %>
		<a href="/albums/<%=album.id%>"
		   data-method="delete"
		   class="btn btn-default btn-small"
		>
		delete album
		</a>
		<a href="/albums/<%=album.id%>/edit"
		   method="get"
		   class="btn btn-primary btn-small"
		>
		edit album
		</a>
		<%end%>
		<br/>
		</blockquote>
	<% end %>
	</div>
<% end %>

<% if current_user and current_user?(@user)%>
<div class="row">
<%= link_to "New Album", new_album_path, :class => "btn btn-large btn-danger" %>
</div>
<br>
<% end %>

<hr>
<% if @friends and !@friends.empty? %>
<div class="span5">
<% @colors = ['success', 'warning', 'info', 'danger','inverse','primary'] %>
	<h2><%= current_user?(@user) ? "your" : @user.name+"'s"  %> friends</h2>
		<% @friends.each do |friend| %>
			<span class="btn btn-<%= @colors.sample %>">
			  <a href="/users/<%= friend.id%>"
				 style="color:white;"
			  ><%= friend.name %></a>
		<% if @user and current_user?(@user) %>
			<a href="/friends/<%=friend.id%>"
			   data-method="delete"
			><i class="icon-white icon-remove"></i></a>
		<%end%>
			</span>
		<%end%>
	<br>
	<br>
	<br>
</div>
<% end%>

<% if @tags and !@tags.empty? %>
<div class="span6">
<% @colors = ['success', 'warning', 'info', 'important','inverse'] %>
	<h2><%= current_user?(@user) ? "your" : @user.name+"'s"  %> tags</h2>
		<% @tags.each do |tag| %>
			<span class="badge badge-<%= @colors.sample %>">
			  <a href="/search/?words=<%= tag.word%>&user=<%= @user.id%>"
				 style="color:white;"
			  ><%= tag.word %></a>
			</span>
		<%end%>
	<br>
	<br>
	<br>
</div>
<% end%>

</div>