config/routes.rb
Flippr::Application.routes.draw do
  
  resources :users  
  resources :albums
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  
  match '/search/', to: 'tags#show'
  match '/popular/', to: "tags#index"
  match '/suggest/', to: "tags#suggest"

  root to: 'users#new'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

end

app/views/shared/_comment.html.erb
<%= form_tag( controller:"comments",action:"create") do %>
	<%= text_field_tag(:text,nil, 
						size:80 ,
						maxlength:300, 
						:placeholder => "...",
						:style => "width:60%;margin:0;")%>
	<input type="hidden" name="photoid" value="<%= photo.id%>" id="photoid" >
	<%= submit_tag("comment", :class => "btn btn-primary")%>
<% end %>

app/views/shared/_photo.html.erb
<tr style="background-color:#F0F0F0;">
	<td width="250">
		<img src="<%= pic.image%>" height=250 width=250>
		<p style="margin:0;background-color:black;color:white;"><%=pic.caption%></p>
	</td>
	<td style="background-color:#F0F0F0;">
		<% pic.comments.each do |comment| %>
			<p>
				<b><%= link_to comment.user.name, user_path(comment.user) %></b>
				<%=comment.text%>
				<span class="muted">| <%= comment.date.strftime("%v") %> </span>
				<% if current_user?(comment.user) %>
					<%= link_to "delete", comment, method: :delete, 
												   confirm: "You Sure?", 
												   title: comment.text, :class => "text-error" %>
				<% end %>
			</p>
		<% end %>
		<% if current_user %>
		<%= render "shared/comment", :photo => pic %>
		<% end %>
	</td>
</tr>
<tr >
	<td class="likes">
	<span style="height:100%;display:inline-block;vertical-align:baseline;">
	<% if current_user %>
		<% @like = current_user.likes(pic); if @like.nil? %>
			<a href="/likes/?photoid=<%= pic.id %>" 
			   data-method="create" 
			   class="btn btn-danger btn-small"
			   >like</a>
		<% else%>
			<a href="/likes/<%=@like.id%>?photoid=<%= pic.id %>" 
			   data-method="delete"
			   class="btn btn-danger btn-small"
			   >unlike</a>
		<% end %>
	<% end %>
		<span class="text-error bold">
			<%= pic.get_likes.count %> likes
		</span><br>
		<% pic.likes.each do |liker| %>
			<%= link_to liker.user.name, user_path(liker.user), :style =>"font-size:9pt;" %>, <%end%>
		</span>
	</td>
	<td class="tags">
	<% @edit_tag = current_user?(pic.get_user) %>
	<% pic.tags.each do |tag| %>
		<span class="badge badge-success">
		  <a href="/search/?words=<%= tag.word%>"
		  	 style="color:white;"
		  ><%= tag.word %></a>
		 <%if @edit_tag%>
			<a href="/tags/<%= pic.id %>?word=<%= tag.word %>"
			   data-method="delete"
			   style="color:black;"
			   ><i class='icon-remove icon-white'></i></a>
		 <%end%>
		</span>
	<%end%>
	<% if @edit_tag %>
		<%= form_tag( controller:"tags",action:"create") do %>
			<%= text_field_tag(:word, nil, size:20, maxlength:20, :style =>"margin:0;" )%>
			<input type="hidden" name="photoid" value="<%=pic.id%>" id="photoid" >
			<%= submit_tag("add tag", :class => "btn")%>
		<% end %>
	<% end %>
	<br>
	<br>
	<br>
	</td>
</tr>