config/routes.rb
Flippr::Application.routes.draw do
  
  resources :users  
  resources :albums
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy]
  resources :friends, only: [:create, :destroy]
  
  match '/search/', to: 'tags#show'
  match '/popular/', to: "tags#index"
  match '/suggest/', to: "tags#suggest"

  root to: 'users#new'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

end

app/models/album.rb
class Album < ActiveRecord::Base
   attr_accessible :userid, :name, :date
  set_table_name 'albums'
  set_primary_key 'id'

  has_many :photos, :foreign_key => "albumid"
  belongs_to :user, :foreign_key => "userid"

  def cover
    Photo.find_by_sql(["SELECT photos.* FROM photos WHERE photos.albumid =? LIMIT 1",id]).first
  end

  def photos
    Photo.find_by_sql(["SELECT photos.* FROM photos WHERE photos.albumid = ?",id])
  end

  def self.from_id(id)
    Album.find_by_sql([
      "SELECT albums.* FROM albums WHERE albums.id = ? LIMIT 1",id]).first
  end

  def destroy
    Album.connection.execute("DELETE FROM albums WHERE albums.id = ?",id) 
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_filter :signed_in_user, only: [:create,:new,:edit, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.limit(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.from_id(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(name:params[:name],date:Time.now(),userid:current_user.id)
    respond_to do |format|
      if @album.save
        
        # add photos
        pics = params[:photo_url].zip(params[:caption]).keep_if{|url,cap| !url.empty? }
        pics.each do |url,cap|
          Photo.create(image:url,caption:cap,albumid:@album.id)
        end
        
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.from_id(params[:id]) 
    respond_to do |format|
      @album.name = (params[:name])
      # update pics
      @pictures = @album.photos
      result = ActiveRecord::Base.transaction do
        res = @pictures.zip(params[:photo_url],params[:caption]).map do |pic,url,cap|
          pic.image = url
          pic.caption = cap
          pic.save
        end
        res.all? && @album.save
      end
      if result
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_tag (@album ? "/albums/#{@album.id}" : '/albums') , method:"put" do %>
  <br>
  <%= submit_tag "Create", :class=>"btn btn-danger" %>
  <br>
  <br>
  <%= label_tag :name, "Album Name (required)" %>
  <%= text_field_tag :name , @album ?  @album.name : nil , :maxlength=>50 %>
  <% @photo = @album.photos if @album%>
  <% @photo.each do |pic| %>
      <%= label_tag 'photo_url[]', "Photo url (one picture required)" %>
      <%= url_field_tag 'photo_url[]',pic.image, :maxlength=>100 %>
      <%= label_tag 'caption[]', "caption" %>
      <%= text_field_tag 'caption[]', pic.caption, :maxlength=>50 %>
  <% end %>
  <%  10.times do %>
      <%= label_tag 'photo_url[]', "Photo url (one picture required)" %>
      <%= url_field_tag 'photo_url[]', nil, :maxlength=>100 %>
      <%= label_tag 'caption[]', "caption" %>
      <%= text_field_tag 'caption[]',nil, :maxlength=>50 %>
  <%  end %>
  <br>
  <%= submit_tag "Create", :class=>"btn btn-danger btn-large" %>
  <br>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Album Name</th>
    <th>User</th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= link_to "#{album.name}", album %></td>
    <td><%= link_to "#{album.user.name}", album.user  %></td>
    <!--<td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice" class="alert-error pagination-centered"><%= notice %></p>

<br>
<h3>album <span class="text-error"><%= @album.name %></span></h3>
<br>

<table>
<% @album.photos.each do |pic| %>
<%= render 'shared/photo', :pic => pic %>
<% end%>
</table>